### Buscar todas as turmas
GET http://localhost:8080/api/v1/turmas

### Buscar Turma pelo ID
GET http://localhost:8080/api/v1/turmas/7644992e-e70a-49b6-9ff2-e6b645d307e8


### Inserir um novo Turma
POST http://localhost:8080/api/v1/turmas
Content-Type: application/json

{
  "nomeTurma": "Turma1",
  "semestre": 1,
  "representante": "Arend" 
}

### Atualizar a Turma
PUT http://localhost:8080/api/v1/turmas/0e177dd4-4313-48a5-86d3-0796886c512a
Content-Type: application/json

{
  
}


### Remover o Turma
DELETE  http://localhost:8080/api/v1/turmas/7644992e-e70a-49b6-9ff2-e6b645d307e8
Content-Type: application/json
