### Buscar todas as turmas
GET http://localhost:8080/api/v1/turmas

### Buscar Turma pelo ID
GET http://localhost:8080/api/v1/turmas/5b71e39f-92ba-4512-9305-bf569fa9e883


### Inserir uma nova Turma
POST http://localhost:8080/api/v1/turmas
Content-Type: application/json

{
  "nomeTurma":"Administração",
  "semestre":3,
  "representante":"aaaaaaaa",
  "listaAlunos":[{
    "nome":"marcas",
    "presenca":true,
    "notas":8.0,
    "matricula":1964875012
  }]

}

### Atualizar a Turma
PUT http://localhost:8080/api/v1/turmas/0e177dd4-4313-48a5-86d3-0796886c512a
Content-Type: application/json

{
  
}


### Remover o Turma
DELETE  http://localhost:8080/api/v1/turmas/fc61f1a6-baa9-42bb-961b-805c85bc567b
Content-Type: application/json






### Buscar professor pelo ID
GET http://localhost:8080/api/v1/professor/d96e83bf-effb-4090-96ca-471921205948

### Inserir professor
POST http://localhost:8080/api/v1/professor
Content-Type: application/json

{
  "matricula":1111111111,
  "nome":"Jurandir",
  "disciplina":"estatistica"
}


